### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Andyauk** [OwenT1/qb-multicharacter#1]
Nice work. but i would to see the use of images, instead of discord links.

**Comment by OwenT1** [comment]
> Nice work. but i would to see the use of images, instead of discord links.

Hey, there is images if you look in the description it says preview

**Comment by Andyauk** [comment]
> > Nice work. but i would to see the use of images, instead of discord links.
> 
> Hey, there is images if you look in the description it says preview

There is yes, but there discord linked images instead of in the folder.

**Comment by Andyauk** [comment]
So what ends up happening is not always the image loads, as it a linked to discord, at the end of the day it's your thing. It's just a suggestion.

**Comment by Andyauk** [comment]
Ps, I hope you do a spawn in the same theme.

**Comment by OwenT1** [comment]
That’s my next task on the list I dunno when I’ll be starting it but I’ll have a think mate

**Comment by Andyauk** [comment]
> That’s my next task on the list I dunno when I’ll be starting it but I’ll have a think mate

I'll close this, but make sure to update your github to the new logo, as they don't show up now you have removed them from discord. Looking forward to a spawn theme maybe with a something other then a zoom effect.
